### ISSUE TITLE
Add documentation about contributing schema changes

### ISSUE THREAD

**Issue by apatard** [ansible/schemas#286]
When trying to add tests in my PR, found out that documentation on how to write test cases is missing.
The negative ones seem to need a markdown file with ajv and check-jsonschema output but I failed to find the commands to run to generate this markdown file.  It would be nice to provide information about this if tests with PR are wanted.

**Comment by ssbarnea** [comment]
@apatard If you could make a PR to add this missing info it would be really great. I think that by now you already know what needs to be done for negative tests:

- add test file in negative_tests directory, with correct filename so we recognize its type
- run `tox -e test` and observe that test fails because the test produced an additional file with expected output. include this file in your change and the test suite should not fail
- once you can run tests locally and they pass, make a pull request
- any change to the schema should include both positive and negative tests

**Comment by apatard** [comment]
ok. Will try to find some time to do it. fwiw, I've not used tox but npm commands directly, since tox was giving me some errors. And it lead me to write the Markdown file by hand (PR for the errors will appear very soon).
